### ISSUE TITLE
Array storage optimization inside `fund()` function for file FundMe.sol

### ISSUE THREAD

**Issue by abraj** [Cyfrin/remix-fund-me-f23#12]
### Description
For the file _FundMe.sol_, the `fund()` function defined executes the following code (_unconditionally_)
```solidity
funders.push(msg.sender);
```
to add the **current sender** address to the `funders` array.

However, this sender might already have sent funds earlier to this smart contract, and therefore 
could be already present in the `funders` array, and (in such cases) there is no need to add that
address again in the `funders` array. So, if an address funds the smart contract 5 times, instead
of adding the same address 5 times in the `funders` array, it would be optimal to add an address
just once.

### Proposed solution
If we add a check for the `push()` function above, we can save the size of the `funders` array in storage.
I believe, there is no in-built way to check the existence of an item in an array in solidity. Also, it's
not optimal to even implement it, as it would anyway take **O(n)** time, which is unnecessary.
Therefore, alternatively, we can use the value stored in the mapping `addressToAmountFunded` 
to decide if we need to add (or not) the address to the `funders` array.

### Sample fix:
```solidity
if (addressToAmountFunded[msg.sender] == 0) {
    funders.push(msg.sender);
}
addressToAmountFunded[msg.sender] += msg.value;
```

I can raise a PR corresponding to this, if it's okay.
Cheers!

**Comment by cromewar** [comment]
Interesting solution to avoid redundancy @abraj, we appreciate this.

@PatrickAlphaC what you think, should we include this as un update to Updraft?

**Comment by PatrickAlphaC** [comment]
We could add this for sure!

I want to keep the code simple for students though, so I'm going to close this. But yes! The way you are thinking is great, and you should keep that way of thinking. Thinking like that will take you far as a smart contract dev.
