### ISSUE TITLE
A bug found in FundMe.sol

### ISSUE THREAD

**Issue by TreapGoGo** [Cyfrin/remix-fund-me-f23#3]
I am not sure if this is a fatal bug, but I still want to put it forward.

Here comes the function `fund()`:

```solidity
function fund() public payable {
        require(msg.value.getConversionRate() >= MINIMUM_USD, "You need to spend more ETH!");
        // require(PriceConverter.getConversionRate(msg.value) >= MINIMUM_USD, "You need to spend more ETH!");
        addressToAmountFunded[msg.sender] += msg.value;
        funders.push(msg.sender);
    }
```

Every time our contract receives a fund from a sender, we add its value to `addressToAmountFunded[msg.sender]` and push the sender's address into `funders`.

Assuming that `0xabcd` called `fund()` for many times, every time with a little money.

The `funders` array will contain many `0xabcd`s, while there is only one `{'0xabcd': total_fund}` in the `addressToAmountFunded` mapping.

Formally speaking, this is not very beautiful. But what's more, it could be a chance for attackers.

If one day we need to calculate how much every funder has funded, the total fund given by those who funded for a lot of times will be counted for a lot of times, which means they may get more rewards or airdrops than they should do.

In this course, such a bug is not fatal, because only the owner of the contract can withdraw money. However, if someone learning this course applies such a bug to a real project, it may bring about a disaster.

I think the right program should judge whether the funder has already been pushed into `funders` before we push. This could make sure that one funder exists only once in `funders`.

**Comment by PatrickAlphaC** [comment]
Yes! I _think_ we call that out at some point in the video, and you're right. This is known as a [Denial of Service attack](https://consensys.github.io/smart-contract-best-practices/attacks/denial-of-service/#dos-with-block-gas-limit). 

However, this code is meant to be educational and not used in production. We take some liberties in the initial lessons to learn. Great find!
