### ISSUE TITLE
The import path of AggregatorV3Interface.sol is again as was in previous FundMe.sol

### ISSUE THREAD

**Issue by lampochka-ds** [Cyfrin/remix-fund-me-f23#5]
When `shared` in path there are an error now. 

https://github.com/Cyfrin/remix-fund-me-f23/blob/ab3e7b1f24dab4da060ab6340568e31b281b7048/FundMe.sol#L4

Helped:
```solidity
- import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol";
+ import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
```

**Comment by 0xValerio** [comment]
please check latest comment on: https://github.com/Cyfrin/remix-fund-me-f23/pull/4

**Comment by Fausi89** [comment]
My head started spinning until I saw "shared" in the path...
at first I just copied the AggregatorV3Interface into my project src folder to go forward, but I wanted to solve this issue at all costs :D

**Comment by PatrickAlphaC** [comment]
Removed, thanks all.

It looks like depending on the CL version you install, it can change the version of remix... I'll see if I can figure out a solution.
